sudo: false

os:
  - linux
# TODO: add osx

language: python

python:
  - "pypy"
  - "2.7"

before_install:
  - pip install -U pip
  - pip install tox tox-travis
  - which python

install:
  - pip install -e .[development]
  - which tox

script: tox

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
