sudo: false

language: python

cache:
  directories:
    - $HOME/.pyenv

matrix:
  include:
    - os: linux
      python: pypy
    - os: linux
      python: 2.7
    - os: osx
      language: generic

before_install:
  - source .travis/before_install.sh

install:
  - source .travis/install.sh

script: tox

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - develop
